version: '2'
services:

  ca-base:
    image: hyperledger/fabric-ca:x86_64-1.0.0
    environment:
      # This is the path to the persistent storage for the CA.
      - FABRIC_CA_HOME=/var/hyperledger/fabric-ca-server
      - FABRIC_CA_LOGGING_LEVEL=$GENERAL_LOGGING_LEVEL
    # The `ls -1 .../*-cert.pem` and `ls -1 .../*_sk` commands are a hack in order to get the hostname-dependent cert filename
    # and randomly generated private key filename.  Not sure why the filename is random.  Maybe this is a security feature.
    command: sh -c 'fabric-ca-server start --ca.certfile `ls -1 /etc/hyperledger/fabric-ca-server/*-cert.pem` --ca.keyfile `ls -1 /etc/hyperledger/fabric-ca-server/*_sk` -b admin:adminpw -d'
